import { dirname } from 'path'
import { fileURLToPath } from 'url'
import { FlatCompat } from '@eslint/eslintrc'

const __filename = fileURLToPath(import.meta.url)
const __dirname  = dirname(__filename)

const compat = new FlatCompat({ baseDirectory: __dirname })

const eslintConfig = [
  // Global ignores — must be a standalone object with only "ignores"
  {
    ignores: [
      '.next/**',        // Next.js build output (webpack bundles, compiled JS)
      'node_modules/**', // Dependencies
      'out/**',          // Static export output
      'public/**',       // Static assets
      'next-env.d.ts',   // Auto-generated by Next.js — never edit manually
      'scripts/**',      // Plain Node.js utility scripts (CommonJS)
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  // Project-wide rule overrides
  {
    rules: {
      // Allow unused variables/parameters prefixed with _ (intentionally unused)
      '@typescript-eslint/no-unused-vars': ['warn', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      }],
    },
  },
]

export default eslintConfig
