// ESLint 10 flat config.
// eslint-config-next 16 ships native flat configs, so the FlatCompat bridge from
// @eslint/eslintrc is gone — ESLint 10 no longer bundles that package anyway.
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypescript from 'eslint-config-next/typescript'

const eslintConfig = [
  // Global ignores — must be a standalone object with only "ignores"
  {
    ignores: [
      '.next/**',        // Next.js build output (webpack bundles, compiled JS)
      'node_modules/**', // Dependencies
      'out/**',          // Static export output
      'public/**',       // Static assets
      'next-env.d.ts',   // Auto-generated by Next.js — never edit manually
      'scripts/**',      // Plain Node.js utility scripts (CommonJS)
      'coverage/**',     // Vitest coverage output
      'graphify-out/**', // Generated codebase graph artifacts
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
  // Project-wide rule overrides
  {
    // Pin the React version explicitly. eslint-plugin-react's auto-detection
    // calls the removed context.getFilename() and crashes on ESLint 10.
    settings: { react: { version: '19.2' } },
    rules: {
      // Allow unused variables/parameters prefixed with _ (intentionally unused)
      '@typescript-eslint/no-unused-vars': ['warn', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      }],
      // New in eslint-plugin-react-hooks 7 (pulled in by eslint-config-next 16).
      // The 20 mounted-flag and load-on-mount hits it originally found are gone:
      // hydration guards run through `useHydrated()`, derived state is computed
      // during render, and every fetch-on-mount writes state only after its
      // await. Kept at 'error' so the pattern does not come back.
      'react-hooks/set-state-in-effect': 'error',
    },
  },
]

export default eslintConfig
